version: '3.9'

services:
  database:
    image: mongo
    container_name: mydbmongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-networks
    environment:
     - MONGO_INITDB_ROOT_USERNAME:root
     - MONGO_INITDB_DATABASE:mydatabase
     - MONGO_INITDB_ROOT_PASSWORD:OptionG2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mongo-networks:
    driver: bridge 

volumes:
  mongo-data:
    external: false