services:
  nest:
    container_name: nest_app
    build: 
      context: ./
    restart: always
    ports:
      - 5000:5000
    environment:
      - DB_URI=mongodb://mongo/mydatabase
      - JWT_SECRET=pruebajwt
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - moonguito

  mongo:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      -  mongo-data:/data/db
      -  mongo-log:/var/log/mongodb
    networks:
      - moonguito
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - moonguito
    restart: always

volumes:
  mongo-data:
    driver: local
    name: mongo-data
  mongo-log:
    driver: local
    name: mongo-log

networks:
  moonguito:
    driver: bridge