name: Call Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    call-publisher:
        uses: alexcham23/project_video_NestJS/.github/workflows/publish.yml@master 
