name: Call Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    call-publish:
        uses: ./project_video_NestJS/project_nest-js/.github/workflows/publish.yml
